# Generated by Django 3.0.6 on 2020-05-31 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.CharField(max_length=300, verbose_name='Search query')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Date and time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_story', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Search query',
                'verbose_name_plural': 'Search story',
                'ordering': ['date_time'],
            },
        ),
        migrations.CreateModel(
            name='LikedVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=50, verbose_name='Video ID')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Date and time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_videos', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Liked video',
                'verbose_name_plural': 'Liked videos',
                'ordering': ['date_time'],
            },
        ),
    ]
