# Generated by Django 3.0.6 on 2020-06-11 11:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likedvideos',
            options={'ordering': ['-date_time'], 'verbose_name': 'Liked video', 'verbose_name_plural': 'Liked videos'},
        ),
        migrations.AlterModelOptions(
            name='searchstory',
            options={'ordering': ['-date_time'], 'verbose_name': 'Search query', 'verbose_name_plural': 'Search story'},
        ),
        migrations.RemoveField(
            model_name='searchstory',
            name='search_query',
        ),
        migrations.RemoveField(
            model_name='searchstory',
            name='user',
        ),
        migrations.AddField(
            model_name='searchstory',
            name='query',
            field=models.CharField(default=django.utils.timezone.now, max_length=300, verbose_name='Query'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SearchCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=50, verbose_name='Video ID')),
                ('video_title', models.CharField(max_length=300, verbose_name='Title')),
                ('video_description', models.CharField(max_length=155, verbose_name='Description')),
                ('video_channel_title', models.CharField(max_length=150, verbose_name='Channel Title')),
                ('video_channel_id', models.CharField(max_length=50, verbose_name='Channel ID')),
                ('video_preview_url', models.CharField(max_length=300, verbose_name='Preview URL')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_cache', to='main.SearchStory', verbose_name='Query')),
            ],
        ),
    ]
