# Generated by Django 3.0.6 on 2020-06-11 11:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200611_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchcache',
            name='video_description',
        ),
        migrations.AddField(
            model_name='searchcache',
            name='video_short_description',
            field=models.CharField(default=django.utils.timezone.now, max_length=155, verbose_name='Short Description'),
            preserve_default=False,
        ),
    ]
