# Generated by Django 3.0.6 on 2020-06-14 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_auto_20200611_1452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likedvideos',
            options={'ordering': ['-date_time'], 'verbose_name': 'Понравившееся видео', 'verbose_name_plural': 'Понравившиеся видео'},
        ),
        migrations.AlterModelOptions(
            name='searchcache',
            options={'verbose_name': 'Кэш поиска', 'verbose_name_plural': 'Кэш поиска'},
        ),
        migrations.AlterModelOptions(
            name='searchstory',
            options={'ordering': ['-date_time'], 'verbose_name': 'Поисковый запрос', 'verbose_name_plural': 'История поиска'},
        ),
        migrations.AlterField(
            model_name='likedvideos',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='likedvideos',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_videos', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='likedvideos',
            name='video_id',
            field=models.CharField(max_length=50, verbose_name='ID Видео'),
        ),
        migrations.AlterField(
            model_name='searchcache',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_cache', to='main.SearchStory', verbose_name='Запрос'),
        ),
        migrations.AlterField(
            model_name='searchcache',
            name='video_channel_id',
            field=models.CharField(max_length=50, verbose_name='ID Канала'),
        ),
        migrations.AlterField(
            model_name='searchcache',
            name='video_channel_title',
            field=models.CharField(max_length=150, verbose_name='Название канала'),
        ),
        migrations.AlterField(
            model_name='searchcache',
            name='video_id',
            field=models.CharField(max_length=50, verbose_name='ID Видео'),
        ),
        migrations.AlterField(
            model_name='searchcache',
            name='video_preview_url',
            field=models.CharField(max_length=300, verbose_name='URL картинки'),
        ),
        migrations.AlterField(
            model_name='searchcache',
            name='video_short_description',
            field=models.CharField(max_length=155, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='searchcache',
            name='video_title',
            field=models.CharField(max_length=300, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='searchstory',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='searchstory',
            name='query',
            field=models.CharField(max_length=300, verbose_name='Запрос'),
        ),
    ]
