# Generated by Django 3.0.7 on 2020-06-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200614_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchcache',
            name='video_short_description',
            field=models.CharField(max_length=300, verbose_name='Краткое описание'),
        ),
    ]
